version: '3.8'
services:
  graphql-challenge:
    image: mzegarra/graphql-challenge-ta:1.0.0
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MSCUSTOMERS_URL=""