spring.application.name: graphql-challenge


dgs:
  graphql:
    schema-locations:
      - "classpath*:schema/**/*.graphql*"
      - "classpath*:schema/**/*.gql"


logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    org.springframework.jdbc.core: ERROR
    #web: DEBUG